require('dotenv').config();
const express = require('express');
const cors = require('cors');
const fetch = require('node-fetch');

const app = express();
const PORT = 3001;

// Your OpenAI API Key
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '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';

// SendGrid API Key (set this in your environment variables)
const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY || '';

// Middleware
app.use(cors()); // Allow requests from frontend
app.use(express.json({ limit: '50mb' })); // Parse JSON bodies

// In-memory storage for doctors and message logs
let doctors = [
  {
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    email: 'sarah.johnson@meditrust.com'
  },
  {
    name: 'Dr. Michael Chen',
    specialty: 'Neurology',
    email: 'michael.chen@meditrust.com'
  },
  {
    name: 'Dr. Priya Sharma',
    specialty: 'General Medicine',
    email: 'priya.sharma@meditrust.com'
  },
  {
    name: 'Dr. James Wilson',
    specialty: 'Pediatrics',
    email: 'james.wilson@meditrust.com'
  },
  {
    name: 'Dr. Emily Rodriguez',
    specialty: 'Dermatology',
    email: 'emily.rodriguez@meditrust.com'
  }
];

let messageLogs = [];

// Rate limiting map (simple in-memory implementation)
const rateLimitMap = new Map();

// Health check endpoint
app.get('/', (req, res) => {
  res.json({ status: 'MediTrust AI Backend is running!' });
});

// Chat endpoint
app.post('/api/chat', async (req, res) => {
  try {
    const { message } = req.body;

    console.log('Received chat request:', message);

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENAI_API_KEY}`
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are a helpful medical AI assistant for MediTrust AI platform. Provide health guidance, answer medical questions, and help users understand their symptoms and health data. Be professional, empathetic, and always recommend consulting with healthcare professionals for serious concerns. Keep responses concise and clear.'
          },
          {
            role: 'user',
            content: message
          }
        ],
        temperature: 0.7,
        max_tokens: 500
      })
    });

    if (!response.ok) {
      const error = await response.text();
      console.error('OpenAI API error:', error);
      throw new Error(`OpenAI API error: ${response.status}`);
    }

    const data = await response.json();
    const reply = data.choices[0].message.content;

    console.log('OpenAI response received');

    res.json({
      reply: reply,
      explanation: 'Response generated by OpenAI GPT-3.5 Turbo - AI-powered medical assistant'
    });

  } catch (error) {
    console.error('Chat error:', error);
    res.status(500).json({
      error: 'Failed to get AI response',
      message: error.message
    });
  }
});

// Image analysis endpoint
app.post('/api/analyze-image', async (req, res) => {
  try {
    const { base64Image } = req.body;

    console.log('Received image analysis request');

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENAI_API_KEY}`
      },
      body: JSON.stringify({
        model: 'gpt-4-vision-preview',
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'text',
                text: 'Analyze this medical image. Describe what you see, identify any potential findings or abnormalities, and provide a confidence level for your observations. Be professional and medical in your analysis.'
              },
              {
                type: 'image_url',
                image_url: {
                  url: `data:image/jpeg;base64,${base64Image}`
                }
              }
            ]
          }
        ],
        max_tokens: 500
      })
    });

    if (!response.ok) {
      const error = await response.text();
      console.error('OpenAI Vision API error:', error);
      throw new Error(`OpenAI Vision API error: ${response.status}`);
    }

    const data = await response.json();
    const analysis = data.choices[0].message.content;

    console.log('Image analysis complete');

    res.json({
      findings: [
        { label: 'AI Analysis Complete', confidence: 0.95 }
      ],
      highlights: [],
      explanation: analysis
    });

  } catch (error) {
    console.error('Image analysis error:', error);
    res.status(500).json({
      error: 'Failed to analyze image',
      message: error.message
    });
  }
});

// Get doctors list
app.get('/api/doctors', (req, res) => {
  try {
    res.json(doctors);
  } catch (error) {
    console.error('Error fetching doctors:', error);
    res.status(500).json({ error: 'Failed to fetch doctors' });
  }
});

// Send message to doctor
app.post('/api/send-message', async (req, res) => {
  try {
    const { doctorEmail, patientName, patientEmail, subject, body } = req.body;

    // Validation
    if (!doctorEmail || !patientName || !body) {
      return res.status(400).json({ 
        error: 'Missing required fields',
        message: 'Doctor email, patient name, and message body are required' 
      });
    }

    if (body.length < 10) {
      return res.status(400).json({ 
        error: 'Message too short',
        message: 'Message must be at least 10 characters long' 
      });
    }

    // Rate limiting (5 messages per IP per hour)
    const clientIp = req.ip || req.connection.remoteAddress;
    const now = Date.now();
    const oneHour = 60 * 60 * 1000;
    
    if (!rateLimitMap.has(clientIp)) {
      rateLimitMap.set(clientIp, []);
    }
    
    const userRequests = rateLimitMap.get(clientIp).filter(time => now - time < oneHour);
    
    if (userRequests.length >= 5) {
      return res.status(429).json({ 
        error: 'Rate limit exceeded',
        message: 'Too many messages sent. Please try again later.' 
      });
    }
    
    userRequests.push(now);
    rateLimitMap.set(clientIp, userRequests);

    // Verify doctor exists
    const doctor = doctors.find(d => d.email === doctorEmail);
    if (!doctor) {
      return res.status(404).json({ 
        error: 'Doctor not found',
        message: 'The selected doctor could not be found' 
      });
    }

    // Log the message
    const messageLog = {
      id: `msg_${Date.now()}`,
      doctorEmail,
      doctorName: doctor.name,
      patientName,
      patientEmail: patientEmail || 'Not provided',
      subject: subject || 'Patient Inquiry',
      body,
      timestamp: new Date().toISOString(),
      status: 'pending'
    };

    // Send email via SendGrid (if API key is configured)
    if (SENDGRID_API_KEY) {
      try {
        const emailResponse = await fetch('https://api.sendgrid.com/v3/mail/send', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${SENDGRID_API_KEY}`
          },
          body: JSON.stringify({
            personalizations: [{
              to: [{ email: doctorEmail, name: doctor.name }],
              subject: subject || 'Patient Inquiry - MediTrust AI'
            }],
            from: {
              email: 'noreply@meditrust.com',
              name: 'MediTrust AI Platform'
            },
            reply_to: patientEmail ? {
              email: patientEmail,
              name: patientName
            } : undefined,
            content: [{
              type: 'text/html',
              value: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                  <h2 style="color: #0E9AA7;">New Patient Message</h2>
                  <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
                    <p><strong>From:</strong> ${patientName}</p>
                    ${patientEmail ? `<p><strong>Email:</strong> ${patientEmail}</p>` : ''}
                    <p><strong>Subject:</strong> ${subject || 'Patient Inquiry'}</p>
                  </div>
                  <div style="background: white; padding: 20px; border-left: 4px solid #0E9AA7;">
                    <p><strong>Message:</strong></p>
                    <p style="white-space: pre-wrap;">${body}</p>
                  </div>
                  <p style="color: #666; font-size: 12px; margin-top: 20px;">
                    This message was sent via MediTrust AI Platform
                  </p>
                </div>
              `
            }]
          })
        });

        if (emailResponse.ok) {
          messageLog.status = 'sent';
          console.log(`✅ Email sent to ${doctorEmail}`);
        } else {
          const errorText = await emailResponse.text();
          console.error('SendGrid error:', errorText);
          messageLog.status = 'failed';
          messageLog.error = errorText;
        }
      } catch (emailError) {
        console.error('Email sending error:', emailError);
        messageLog.status = 'failed';
        messageLog.error = emailError.message;
      }
    } else {
      // No SendGrid key - simulate success
      console.log('⚠️  SendGrid not configured - simulating email send');
      console.log(`📧 Would send to: ${doctorEmail}`);
      console.log(`From: ${patientName} (${patientEmail || 'no email'})`);
      console.log(`Subject: ${subject || 'Patient Inquiry'}`);
      console.log(`Message: ${body}`);
      messageLog.status = 'simulated';
    }

    messageLogs.push(messageLog);

    res.json({
      success: true,
      message: 'Message sent successfully to doctor',
      messageId: messageLog.id,
      status: messageLog.status
    });

  } catch (error) {
    console.error('Send message error:', error);
    res.status(500).json({
      error: 'Failed to send message',
      message: error.message
    });
  }
});

// Get message logs (optional - for admin purposes)
app.get('/api/message-logs', (req, res) => {
  try {
    res.json(messageLogs);
  } catch (error) {
    console.error('Error fetching message logs:', error);
    res.status(500).json({ error: 'Failed to fetch message logs' });
  }
});

app.listen(PORT, () => {
  console.log(`🚀 MediTrust AI Backend running on http://localhost:${PORT}`);
  console.log(`✅ Ready to handle AI requests`);
  console.log(`📧 SendGrid configured: ${SENDGRID_API_KEY ? 'Yes' : 'No (using simulation mode)'}`);
});
